import React, { Component } from 'react';

export default class App extends Component {
  render() {
    return (
    	<div className="app">
	      	<div className="controls form-inline">
	      		<div className="form-group">
		      		<select className="form-control">
		      			<option>9x9</option>
		      			<option>16x16</option>
		      			<option>16x30</option>
		      		</select>
		      		<button className="btn btn-primary">Restart</button>
	      		</div>
	      	</div>
	      	<div className="game s16x30">
	      		<div className="minerow">
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn selected one">1</button>
	      			<button className="btn selected two">2</button>
	      			<button className="btn selected three">3</button>
	      			<button className="btn selected four">4</button>
	      			<button className="btn selected five">5</button>
	      			<button className="btn selected six">6</button>
	      			<button className="btn selected seven">7</button>
	      			<button className="btn selected eight">8</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn selected">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn flag">&nbsp;</button>
	      			<button className="btn selected bomb">&nbsp;</button>
	      			<button className="btn selected bomb wrong">&nbsp;</button>
	      			<button className="btn selected bomb step">&nbsp;</button>
	      		</div>
	      		<div className="minerow">
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      		</div>
	      		<div className="minerow">
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      		</div>
	      		<div className="minerow">
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      		</div>
	      		<div className="minerow">
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      		</div>
	      		<div className="minerow">
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      		</div>
	      		<div className="minerow">
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      		</div>
	      		<div className="minerow">
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      		</div>
	      		<div className="minerow">
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      		</div>
	      		<div className="minerow">
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      		</div>
	      		<div className="minerow">
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      		</div>
	      		<div className="minerow">
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      		</div>
	      		<div className="minerow">
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      		</div>
	      		<div className="minerow">
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      		</div>
	      		<div className="minerow">
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      		</div>
	      		<div className="minerow">
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      		</div>
	      		<div className="minerow">
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      		</div>
	      		<div className="minerow">
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      		</div>
	      		<div className="minerow">
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      		</div>
	      		<div className="minerow">
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      		</div>
	      		<div className="minerow">
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      		</div>
	      		<div className="minerow">
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      		</div>
	      		<div className="minerow">
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      		</div>
	      		<div className="minerow">
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      		</div>
	      		<div className="minerow">
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      		</div>
	      		<div className="minerow">
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      		</div>
	      		<div className="minerow">
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      		</div>
	      		<div className="minerow">
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      		</div>
	      		<div className="minerow">
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      		</div>
	      		<div className="minerow">
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      			<button className="btn">&nbsp;</button>
	      		</div>
	      	</div>
      	</div>
    );
  }
}
